### ISSUE TITLE
css

### ISSUE THREAD

**Issue by acsantosac** [GPLEI16/Site#10]
Gostaria de saber qual o ficheiro de css a ser utilizado do master.

estilo.css e/ou geral.css

**Comment by Mica100tempo** [comment]
É uma boa pergunta andré, pelo que tenho visto tens de incluir os 2 em cada página:
  <link rel="stylesheet" type="text/css" href="css/estilo.css" /> (alterando o link)
  <link rel="stylesheet" type="text/css" href="css/geral.css" />

**Comment by acsantosac** [comment]
Seria importante os responsáveis pelas css contornar e eliminar o que estiver duplicado para não existir conflitos.
